// Tenax Phase B7 — Landing Page & Judge Journey tests.
// Offline, zero network, zero credentials, zero Bitget/AI/Telegram calls.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { SESSION_ONLY_NOTICE } from "../src/app/app/_copy";

describe("Landing Page & Judge Journey (Phase B7)", () => {
  const landingSource = readFileSync(
    resolve(process.cwd(), "src/app/page.tsx"),
    "utf8",
  );
  const layoutSource = readFileSync(
    resolve(process.cwd(), "src/app/layout.tsx"),
    "utf8",
  );
  const shellNavSource = readFileSync(
    resolve(process.cwd(), "src/app/app/_components/ShellNav.tsx"),
    "utf8",
  );

  describe("Metadata and Branding", () => {
    it("root layout has brand-aligned Tenax metadata instead of starter template", () => {
      expect(layoutSource).toContain("Tenax — Bounded Autonomy for Tokenized Equities");
      expect(layoutSource).not.toContain("Create Next App");
      expect(layoutSource).not.toContain("Generated by create next app");
    });
  });

  describe("Hero Section & Thesis", () => {
    it("features the exact required headline and thesis copy", () => {
      expect(landingSource).toContain("Give AI permission to act.");
      expect(landingSource).toContain("Not unlimited control of your capital.");
      expect(landingSource).not.toContain("Give AI permission to act —");
      expect(landingSource).toContain(
        "Tenax lets tokenized equity holders define standing protection mandates.",
      );
      expect(landingSource).toContain("AI analyzes the event and proposes what to do.");
      expect(landingSource).toContain(
        "Deterministic rules decide what the agent is actually allowed to execute.",
      );
      expect(landingSource).toContain("AGENTIC TRADING");
      expect(landingSource).toContain("CROSS-ASSET EXECUTION AGENT");
      expect(landingSource).toContain("EVENT → DECISION → EXECUTION → PROOF");
    });

    it("has working primary and secondary judge CTAs", () => {
      expect(landingSource).toContain('href="/app/protect/nvidia"');
      expect(landingSource).toContain("LAUNCH NVIDIA PROTECTION");
      expect(landingSource).toContain('href="/app/proof"');
      expect(landingSource).toContain("VIEW VERIFIED DECISIONS");
      expect(landingSource).toContain('href="/app/mandate"');
      expect(landingSource).toContain("INSPECT STANDING MANDATE");
      expect(landingSource).toContain('href="/app/connected"');
      expect(landingSource).toContain("PERSONAL BITGET ACCOUNTS");
      expect(landingSource).toContain("Bring your own portfolio into Tenax.");
      expect(landingSource).toContain("COMING SOON — HOSTED CONNECTION");
      expect(landingSource).not.toContain("USE YOUR OWN ACCOUNT");
      expect(landingSource).not.toContain("CONNECTED · READ ONLY");
      expect(landingSource).not.toContain("INSTALL TENAX CONNECTOR");
      expect(landingSource).not.toContain("CONNECTED USER TRADING");
    });

    it("includes the 4-part truth and status strip", () => {
      expect(landingSource).toContain("LIVE BITGET MARKET DATA");
      expect(landingSource).toContain("SIMULATED NVIDIA EXPOSURE");
      expect(landingSource).toContain("BITGET DEMO · VIRTUAL FUNDS");
      expect(landingSource).toContain("DURABLE DECISION PROOF");
    });

    it("includes the Tenax Sentinel asset-backed mascot", () => {
      expect(landingSource).toContain("<TenaxAgent");
      expect(landingSource).toContain('state="watching"');
      expect(landingSource).toContain("SENTINEL · ACTIVE");
    });
  });

  describe("How Tenax Works & Transformation Pipeline", () => {
    it("explains the 6 sequential stages of the bounded lifecycle", () => {
      expect(landingSource).toContain("01 EXPOSURE");
      expect(landingSource).toContain("02 INTENT");
      expect(landingSource).toContain("03 INTELLIGENCE");
      expect(landingSource).toContain("04 MANDATE");
      expect(landingSource).toContain("05 ACTION");
      expect(landingSource).toContain("06 PROOF");
    });

    it("contains the core pipeline transformation diagram", () => {
      expect(landingSource).toContain("AI PROPOSAL");
      expect(landingSource).toContain("DETERMINISTIC MANDATE EVALUATION");
      expect(landingSource).toContain("EXECUTE");
      expect(landingSource).toContain("ESCALATE");
      expect(landingSource).toContain("REFUSE");
    });
  });

  describe("Example Standing Mandate", () => {
    it("shows concrete permissions and bounded authority behavior", () => {
      expect(landingSource).toContain("EXAMPLE MANDATE");
      expect(landingSource).toContain("SUBJECT");
      expect(landingSource).toContain("NVIDIA");
      expect(landingSource).toContain("NVDAUSDT");
      expect(landingSource).toContain("30%");
      expect(landingSource).toContain("$100");
      expect(landingSource).toContain("1X");
      expect(landingSource).toContain("MAX EXECUTIONS");
      expect(landingSource).toContain("SELL UNDERLYING");
      expect(landingSource).toContain("TRANSFERS");
      expect(landingSource).toContain("NEVER");
      expect(landingSource).toContain("AUTO WITH ESCALATION");
      expect(landingSource).toContain("INSIDE BOUNDS");
      expect(landingSource).toContain("Tenax may act automatically.");
      expect(landingSource).toContain("OUTSIDE DELEGATED BOUNDS");
      expect(landingSource).toContain("Human review required.");
      expect(landingSource).toContain("The agent does not receive unlimited discretion.");
      expect(landingSource).toContain("It receives a mandate.");
    });
  });

  describe("Three Outcomes Story", () => {
    it("presents Execute, Escalate, and Refuse as bounded autonomy features", () => {
      // Execute
      expect(landingSource).toContain("Execute Within Bounds");
      expect(landingSource).toContain("INSIDE MANDATE · AUTONOMOUS");
      expect(landingSource).toContain("Bounded by max protection %, max notional, and 1x leverage.");

      // Escalate
      expect(landingSource).toContain("Escalate to Human Review");
      expect(landingSource).toContain("OUTSIDE NUMERIC BOUNDS · REVIEW");
      expect(landingSource).toContain("No autonomous order sent. Standing budget stays untouched.");

      // Refuse
      expect(landingSource).toContain("Refuse Unsafe Actions");
      expect(landingSource).toContain("HARD SAFETY FAILURE · BLOCKED");
      expect(landingSource).toContain("Refusal is a first-class feature.");
      expect(landingSource).toContain("Hard stop. No order sent.");
    });
  });

  describe("Real Proof Preview", () => {
    it("queries getProofRepository and handles both populated and empty/error states", () => {
      expect(landingSource).toContain("getProofRepository()");
      expect(landingSource).toContain("listProofs({ limit: 3 })");
      expect(landingSource).toContain("VIEW ALL PROOFS");
      expect(landingSource).toContain(
        "DURABLE POSTGRES LEDGER ACTIVE · AWAITING FIRST TERMINAL OUTCOME",
      );
      expect(landingSource).toContain("DURABLE HISTORY UNAVAILABLE");
    });

    it("strictly checks durability backend and durabilityState so memory is never presented as durable", () => {
      expect(landingSource).toContain('handle.backend === "POSTGRES"');
      expect(landingSource).toContain('handle.durabilityState !== "DURABLE"');
      expect(landingSource).toContain("DATABASE_URL is not configured. Ephemeral session state is never presented as verified proof.");
    });

    it("displays mandatory truth disclaimer about historical records", () => {
      expect(landingSource).toContain(
        "Historical record only — does not imply an open position or current PnL.",
      );
    });
  });

  describe("Differentiation & Core Thesis", () => {
    it("communicates the permission over capability distinction", () => {
      expect(landingSource).toContain(
        "Most agent systems focus on what an agent can do. Tenax focuses on what the agent is",
      );
      expect(landingSource).toContain("allowed to do");
    });

    it("lists the 5 institutional architecture pillars", () => {
      expect(landingSource).toContain("Programmable Capital Intent");
      expect(landingSource).toContain("Bounded Standing Authority");
      expect(landingSource).toContain("Deterministic Enforcement");
      expect(landingSource).toContain("Escalation Instead of Overreach");
      expect(landingSource).toContain("Durable Decision Receipts");
    });
  });

  describe("Judge Journey Quick Start", () => {
    it("provides the 5-step quickstart roadmap for hackathon evaluators", () => {
      expect(landingSource).toContain("01 READ THESIS");
      expect(landingSource).toContain("PROOF PREVIEW");
      expect(landingSource).toContain("02 CONFIGURE STANDING MANDATE");
      expect(landingSource).toContain("03 LAUNCH NVIDIA PROTECTION");
      expect(landingSource).toContain("04 OBSERVE GATE");
      expect(landingSource).toContain("05 VERIFY RECEIPT");
    });
  });

  describe("Navigation Integration & Shell", () => {
    it("includes PROOF in ShellNav so judges can access proof from anywhere", () => {
      expect(shellNavSource).toContain('href: "/app/proof"');
      expect(shellNavSource).toContain('label: "PROOF"');
    });

    it("landing page header contains navigation to all primary app destinations", () => {
      expect(landingSource).toContain('href="/app"');
      expect(landingSource).toContain('href="/app/protect/nvidia"');
      expect(landingSource).toContain('href="/app/mandate"');
      expect(landingSource).toContain('href="/app/proof"');
      expect(landingSource).toContain('href="/app/activity"');
      expect(landingSource).toContain("PERSONAL ACCOUNTS");
      expect(landingSource).toContain('href="/app/connected"');
    });

    it("resolves dynamic execution mode for truthful capability display", () => {
      expect(landingSource).toContain("resolveExecutionMode(process.env)");
    });
  });

  describe("Copy Debt Remediation", () => {
    it("SESSION_ONLY_NOTICE is updated to reflect Postgres proof separation", () => {
      expect(SESSION_ONLY_NOTICE).not.toContain("No database yet.");
      expect(SESSION_ONLY_NOTICE).toContain(
        "Verified decision proof is stored separately in durable history.",
      );
    });
  });
});
