// Tenax public landing page — content + truth contract (source-level).
// Offline, zero network, zero credentials, zero Bitget/AI/Telegram calls.
import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { SESSION_ONLY_NOTICE } from "../src/app/app/_copy";
import { AUTHORITY_OUTCOMES } from "../src/app/_landing/OutcomeCarousel";
import {
  MANDATE_FIXTURE,
  NVDA_EXPOSURE_FIXTURE,
  PROPOSAL_REFUSE_VALUE_FIXTURE,
} from "../src/lib/tenax/fixtures";
import { evaluateMandate } from "../src/lib/tenax/mandate";

const read = (path: string): string => readFileSync(resolve(process.cwd(), path), "utf8");

const landingSource = read("src/app/page.tsx");
const devicesSource = read("src/app/_landing/devices.tsx");
const carouselSource = read("src/app/_landing/OutcomeCarousel.tsx");
const flowSource = read("src/app/_landing/AuthorityFlow.tsx");
const layoutSource = read("src/app/layout.tsx");
const shellNavSource = read("src/app/app/_components/ShellNav.tsx");
const allLanding = [landingSource, devicesSource, carouselSource, flowSource]
  .join("\n")
  .split("\n")
  .filter((line) => !line.trim().startsWith("//"))
  .join("\n");

describe("Metadata and Branding", () => {
  it("root layout has brand-aligned Tenax metadata instead of starter template", () => {
    expect(layoutSource).toContain("Tenax — Bounded Autonomy for Tokenized Equities");
    expect(layoutSource).not.toContain("Create Next App");
    expect(layoutSource).not.toContain("Generated by create next app");
  });
});

describe("Hero", () => {
  it("carries the required headline, thesis copy and judge CTA", () => {
    expect(landingSource).toContain("Give AI limits");
    expect(landingSource).toContain("before you give it");
    expect(landingSource).toContain("execution.");
    expect(landingSource).toContain(
      "Tenax turns AI trading intent into governed action. Every proposal passes through deterministic mandates, human authority where required, and durable decision evidence before an order can move.",
    );
    expect(landingSource).toContain("SEE TENAX IN ACTION");
    expect(landingSource).toContain('href="/app/protect/nvidia"');
  });

  it("presents the system strip as capabilities, never as partner logos", () => {
    for (const label of ["BITGET MCP", "BITGET DEMO", "AI ANALYSIS", "DETERMINISTIC MANDATES"]) {
      expect(landingSource).toContain(label);
    }
    expect(landingSource).toContain("BUILT AROUND");
    expect(allLanding).not.toMatch(/trusted by|our partners|partnered with/i);
  });

  it("resolves the execution mode server-side for truthful display", () => {
    expect(landingSource).toContain("resolveExecutionMode(process.env)");
    expect(landingSource).not.toContain("□ DRY_RUN");
    expect(landingSource).not.toContain("□ BITGET_DEMO");
    expect(landingSource).not.toContain('"use client"');
    expect(landingSource).not.toContain("NEXT_PUBLIC");
  });
});

describe("Device mockups", () => {
  it("are labelled illustrative and render demo fixtures through the real mandate engine", () => {
    expect(devicesSource).toContain("ILLUSTRATIVE · DEMO FIXTURE");
    expect(landingSource).toContain("evaluateMandate(");
    expect(landingSource).toContain("PROPOSAL_REFUSE_VALUE_FIXTURE");
    expect(landingSource).toContain("MANDATE_FIXTURE");
    expect(devicesSource).toContain("EVENT ROOM");
    expect(devicesSource).toContain("FINAL TENAX DECISION");
    expect(devicesSource).toContain("DECISION PROOF");
    expect(devicesSource).toContain("NO ORDER SENT");
    expect(devicesSource).toContain("UNVERIFIED");
  });

  it("the depicted verdict is what the deterministic engine actually returns", () => {
    const decision = evaluateMandate(
      PROPOSAL_REFUSE_VALUE_FIXTURE,
      MANDATE_FIXTURE,
      NVDA_EXPOSURE_FIXTURE,
      "demo-fixture",
    );
    expect(decision.verdict).toBe("REFUSE");
    expect(decision.failedRules).toEqual(["max_protection_pct", "max_trade_value"]);
  });

  it("are a single accessible image with decorative internals", () => {
    expect(devicesSource).toContain('role="img"');
    expect(devicesSource).toContain('aria-hidden="true"');
  });
});

describe("Dedicated hero art", () => {
  const artSource = read("src/app/_landing/HeroArt.tsx");

  const artPath = resolve(process.cwd(), "public/brand/tenax-agent-hero.png");

  it("targets the dedicated hero PNG and requires the file once approved", async () => {
    const { HERO_ART } = await import("../src/app/_landing/hero-art");
    expect(HERO_ART.src).toBe("/brand/tenax-agent-hero.png");
    if (HERO_ART.approved) expect(existsSync(artPath)).toBe(true);
  });

  it.runIf(existsSync(artPath))("the PNG is real RGBA with intrinsic dimensions matching the config", async () => {
    const { HERO_ART } = await import("../src/app/_landing/hero-art");
    const file = readFileSync(artPath);
    expect(file.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
    expect(file.readUInt32BE(16)).toBe(HERO_ART.width);
    expect(file.readUInt32BE(20)).toBe(HERO_ART.height);
    // RGBA renders sit on the field directly; RGB renders must declare
    // alpha:false so the opaque-ground compositing fallback is applied.
    expect([2, 6]).toContain(file[25]);
    expect(HERO_ART.alpha).toBe(file[25] === 6);
  });

  it("is live behind the owner approval gate and replaces the old composition", async () => {
    const { HERO_ART } = await import("../src/app/_landing/hero-art");
    expect(HERO_ART.approved).toBe(true);
    expect(landingSource).toContain("HERO_ART.approved ? (");
    expect(landingSource).toContain("<HeroArt />");
    expect(landingSource).not.toContain("MascotHero");
    expect(landingSource).not.toContain("HeroDevices");
    expect(existsSync(resolve(process.cwd(), "src/app/_landing/MascotHero.tsx"))).toBe(false);
  });

  it("composites an opaque render away instead of showing a box", () => {
    expect(artSource).toContain('HERO_ART.alpha ? "" : " tx-hero-art-opaque"');
    const css = read("src/app/_landing/landing.css");
    expect(css).toMatch(/\.tx-hero-art-opaque \.tx-hero-art-img \{\s*mix-blend-mode: lighten;/);
  });

  it("is the whole visual: no HTML phones layered over the render", () => {
    expect(artSource).toContain('from "next/image"');
    expect(artSource).toContain("HERO_ART.src");
    expect(artSource).not.toContain("unoptimized");
    for (const forbidden of ["Phone", "EventScreen", "DecisionScreen", "tx-phone"]) {
      expect(artSource).not.toContain(forbidden);
    }
  });

  it("never leaks into the application, which keeps the original mascot", () => {
    const appFiles = [
      "src/app/app/_components/living.tsx",
      "src/app/app/_components/AgentFigure.tsx",
      "src/app/app/layout.tsx",
    ];
    for (const file of appFiles) expect(read(file)).not.toContain("tenax-agent-hero");
    expect(read("src/app/app/_components/living.tsx")).toContain('"/brand/tenax-agent.png"');
  });
});

describe("Storytelling section", () => {
  it("states the authority thesis and truthful system facts only", () => {
    expect(landingSource).toContain("AI can suggest the trade.");
    expect(landingSource).toContain("Tenax decides whether");
    expect(landingSource).toContain("it has authority.");
    expect(landingSource).toContain("Models are probabilistic. Execution authority shouldn&apos;t be.");
    expect(landingSource).toContain("SELF-AUTHORIZED ORDERS");
    expect(landingSource).toContain("AUTHORITY OUTCOMES");
    expect(landingSource).toContain("DURABLE EVIDENCE CHAIN");
    expect(landingSource).toContain("PASS · REFUSE · ESCALATE · REVIEW");
  });

  it("renders the decision-network flow across every authority stage", () => {
    for (const stage of ["EVENT", "AI INTENT", "MANDATE", "HUMAN AUTHORITY", "EXECUTOR", "PROOF"]) {
      expect(flowSource).toContain(`label: "${stage}"`);
    }
  });
});

describe("Intent → authorized action cards", () => {
  it("has the three required cards with exact copy", () => {
    expect(landingSource).toContain("From intent");
    expect(landingSource).toContain("to authorized action.");
    expect(landingSource).toContain('title: "AI INTENT"');
    expect(landingSource).toContain('title: "MANDATE GATE"');
    expect(landingSource).toContain('title: "DECISION EVIDENCE"');
    expect(landingSource).toContain("without granting the model execution authority.");
    expect(landingSource).toContain(
      "Deterministic rules decide whether the proposal is permitted, refused, escalated, or requires human review.",
    );
    expect(landingSource).toContain(
      "Every terminal decision preserves what the AI proposed, what authority decided, and what actually happened.",
    );
  });
});

describe("FAQ", () => {
  it("uses native, accessible details/summary with all six questions", () => {
    expect(landingSource).toContain("Curious about");
    expect(landingSource).toContain("<details");
    expect(landingSource).toContain("<summary");
    for (const q of [
      "CAN THE AI TRADE BY ITSELF?",
      "WHAT HAPPENS IF THE AI PROPOSES SOMETHING DANGEROUS?",
      "WHAT EXACTLY IS A MANDATE?",
      "WHAT'S THE DIFFERENCE BETWEEN REFUSE AND A FAILED TRADE?",
      "DOES TENAX ASSUME THE AI IS ALWAYS RIGHT?",
      "HOW DO I KNOW WHAT ACTUALLY HAPPENED?",
    ]) {
      expect(landingSource).toContain(q);
    }
  });
});

describe("Authority outcomes", () => {
  it("presents the four first-class outcomes as system states", () => {
    expect(AUTHORITY_OUTCOMES.map((o) => o.name)).toEqual(["REFUSE", "ESCALATE", "PASS", "REVIEW REQUIRED"]);
    expect(AUTHORITY_OUTCOMES[0].result).toBe("NO ORDER SENT");
    expect(AUTHORITY_OUTCOMES[1].result).toBe("NO AUTONOMOUS ORDER SENT");
    expect(landingSource).toContain("See what");
    expect(landingSource).toContain("authority looks like.");
  });

  it("carousel controls are labelled buttons", () => {
    expect(carouselSource).toContain('aria-label="Previous outcome"');
    expect(carouselSource).toContain('aria-label="Next outcome"');
    expect(carouselSource).toContain('aria-roledescription="carousel"');
  });
});

describe("Closing CTA and footer", () => {
  it("has the closing statement and app CTA", () => {
    expect(landingSource).toContain("AI shouldn&apos;t be");
    expect(landingSource).toContain("its own risk officer.");
    expect(landingSource).toContain("OPEN TENAX");
    expect(landingSource).toContain("It cannot authorize itself.");
  });
});

describe("Truth discipline", () => {
  it("fabricates no social proof, adoption, or performance", () => {
    expect(allLanding).not.toMatch(/testimonial|\busers\b|traders trust|countries|win rate|\bAPY\b|\bROI\b|returns of/i);
    expect(allLanding).not.toMatch(/\d+\s?[kKmM]\+|\$\d+[kKmMbB]\b/);
  });

  it("links only to existing app routes or on-page sections", () => {
    const hrefs = [...landingSource.matchAll(/href: "([^"]+)"|href="([^"]+)"/g)].map((m) => m[1] ?? m[2]);
    expect(hrefs.length).toBeGreaterThan(10);
    for (const href of hrefs) {
      if (href.startsWith("#")) {
        expect(landingSource).toContain(`id="${href.slice(1)}"`);
        continue;
      }
      expect(href.startsWith("/")).toBe(true);
      const page = href === "/" ? "src/app/page.tsx" : `src/app${href}/page.tsx`;
      expect(existsSync(resolve(process.cwd(), page)), href).toBe(true);
    }
  });
});

describe("Navigation Integration & Shell", () => {
  it("includes PROOF in ShellNav so judges can access proof from anywhere", () => {
    expect(shellNavSource).toContain('href: "/app/proof"');
    expect(shellNavSource).toContain('label: "PROOF"');
  });

  it("always offers a return path from the app shell to the landing page", () => {
    const appShellSource = read("src/app/app/layout.tsx");
    expect(appShellSource).toContain('<TenaxWordmark href="/"');
    expect(appShellSource).toContain("BACK TO SITE");
    expect(appShellSource).toContain('href="/"');
    expect(shellNavSource).toContain("← BACK TO SITE");
  });

  it("landing navigation exposes the product sections and the app", () => {
    for (const label of ["Product", "How It Works", "Authority", "Evidence", "OPEN APP"]) {
      expect(landingSource).toContain(label);
    }
    expect(landingSource).toContain('href="/app"');
  });
});

describe("Copy Debt Remediation", () => {
  it("SESSION_ONLY_NOTICE is updated to reflect Postgres proof separation", () => {
    expect(SESSION_ONLY_NOTICE).not.toContain("No database yet.");
    expect(SESSION_ONLY_NOTICE).toContain(
      "Verified decision proof is stored separately in durable history.",
    );
  });
});
